config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index] do
    resources :secrets, :only => [:new]
  end
  resource :session, :only => [:create, :destroy, :new]

  resources :secrets, :only => [:create]

  resources :friendships, :only => [:create]

  post "friendships/delete", :to => "friendships#special_delete"

  root :to => "users#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :in_friend_id, :out_friend_id

  validates :in_friend_id, :out_friend_id, :presence => true

  belongs_to :in_friend, :class_name => "User"
  belongs_to :out_friend, :class_name => "User"

  def self.can_friend?(out_friend_id, in_friend_id)
    !Friendship.exists?(:out_friend_id => out_friend_id,
                        :in_friend_id => in_friend_id) &&
      out_friend_id != in_friend_id
  end

  def self.get_friendship(outf, inf)
    Friendship.find_by_out_friend_id_and_in_friend_id(outf, inf)
  end
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :title

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  has_many :taggings
  has_many :tags, :through => :taggings, :source => :tag

  validates :author_id, :recipient_id, :title, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true

  has_many :taggings
  has_many :secrets, :through => :taggings, :source => :secret
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  attr_accessible :tag_id, :secret_id

  validates :tag_id, :secret_id, :presence => true

  belongs_to :tag
  belongs_to :secret

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    sleep(0.5)

    @friendship = Friendship.new(params[:friendship])
    @friendship.out_friend_id = current_user.id
    @friendship.save!

    redirect_to users_url
  end

  def special_delete
    sleep(0.5)
    Friendship.get_friendship(params[:out_friend_id], params[:in_friend_id]).destroy
    head :ok
  end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController

  def new
    @user = User.find(params[:user_id])

    render :new
  end

  def create
    @secret = Secret.new(params[:secret])
    @secret.author_id = current_user.id
    @secret.save!
    redirect_to @secret.recipient
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<form action="/secrets" method="POST">
  <label for="secret_title">Title</label>
  <input type="text" id="secret_title" name="secret[title]"></input>

  <input type="hidden" name="secret[recipient_id]"
    value="<%= @user.id %>"></input>

  <input type="submit" value="Post secret!"></input>


</form>

app/views/secrets/new.html.erb
<%= render :partial => "form" %>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<h2>Users</h2>

<ul>
  <% @users.each do |user| %>
    <% next if user == current_user %>

    <% if Friendship.get_friendship(current_user.id, user.id) %>
      <% class_name = "can-unfriend" %>
    <% else %>
      <% class_name = "can-friend" %>
    <% end %>

    <li>
      <%= user.username %>
      <div class="friend-buttons <%= class_name %>">
        <button class="friend" data_id="<%= user.id %>">Add friend</button>
        <button class="unfriend" data_id="<%= user.id %>">Remove friend</button>
      </div>
    </li>
  <% end %>
</ul>

<script>
  $(".friend").on("click", function(event) {
    console.log($(this).attr("data_id"))

    var button = this;

    $(this).text("Friending...");
    $(this).attr("disabled", "disabled");

    $.ajax({
      type: "POST",
      url: "/friendships",
      data: {
        friendship: {
          in_friend_id: $(button).attr("data_id"),
          out_friend_id: <%= current_user.id %>
        }
      },
      success: function (response) {
        $(button).text("Add friend");
        $(button).removeAttr("disabled");
        console.log("success friend: "+button);
        $(button).parent().toggleClass("can-friend can-unfriend");
      }
    })
  });

  $(".unfriend").on("click", function(event) {
    console.log("unfriend"+$(this).attr("data_id"))

    var button = this;

    $(this).text("Unfriending...");
    $(this).attr("disabled", "disabled");

    $.ajax({
      type: "POST",
      url: "/friendships/delete",
      data: {
        in_friend_id: $(button).attr("data_id"),
        out_friend_id: <%= current_user.id %>
      },
      success: function () {
        $(button).text("Remove friend");
        $(button).removeAttr("disabled");
        console.log("success unfriend: "+button)
        $(button).parent().toggleClass("can-friend can-unfriend");
      }
    })
  });

</script>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Secrets</h2>

<ul class="secrets">
  <% @user.received_secrets.each do |secret| %>
    <li><%= secret.title %></li>
  <% end %>
</ul>

<label for="secret-text">Title</label>
<input type="text" id="secret-text">

<select class="tag-selector" name="select">
</select>

<button class="secret-btn">Add secret</button>

<script type="application/json" id="bootstrapped_tags_json">
  { "tags": <%= Tag.all.to_json.html_safe %> }
</script>

<script type="text/template" id="widgets_template">
  <%% _(data["tags"]).each(function(tag) { %>
    <option value="<%%= tag["name"] %>"><%%= tag["name"] %></option>
  <%% }); %>
</script>

<script>
  var data = JSON.parse($("#bootstrapped_tags_json").html());

  var templateCode = $('#tags_template').html();
  var templateFn = _.template(templateCode);
  var renderedContent = templateFn(data);
  console.log(renderedContent)
  $(".tag-selector").html(renderedContent);

  $(".secret-btn").on("click", function (event) {
    var text = $("#secret-text").val();
    $.ajax({
      type: "POST",
      url: "/secrets",
      data: {
        secret: {
          title: $("#secret-text").val(),
          author_id: <%= current_user.id %>,
          recipient_id: <%= @user.id %>
        }
      },
      success: function () {
        $(".secrets").prepend("<li>"+text+"</li>")
      }
    });
    $("#secret-text").val('')
  })

</script>

<%#= render partial: "secrets/form" %>